services:
  db:
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
    - mariadb_auth_system_data:/var/lib/mysql
    - ./db/init:/docker-entrypoint-initdb.d
    restart: no
    ports:
      - "3306:3306"
  
volumes:
  mariadb_auth_system_data:
