CREATE DATABASE IF NOT EXISTS auth_system;

USE auth_system;

CREATE TABLE IF NOT EXISTS users (
    id UUID NOT NULL DEFAULT UUID() PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    isActive BOOLEAN DEFAULT TRUE
);